apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-1
  namespace: live
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
        - name: my-live-container
          image: imageTag
          ports:
            - containerPort: 3000
          startupProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - app-1
              topologyKey: "kubernetes.io/hostname"      


---
### service.yaml
apiVersion: v1
kind: Service
metadata:
  name: app-svc-1
  namespace: live
spec:
  selector:
    app: app-1
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
